export const maintenanceRquests = [
  {
    title: "Leaky Faucet",
    description: "The kitchen faucet has a continuous leak.",
    request_date: 1694776200000,
    resolved_date: null,
    status: "in-progress",
    urgency: "medium",
  },
  {
    title: "Broken Window",
    description: "The living room window is shattered.",
    request_date: 1694330400000,
    resolved_date: 1694512800000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Heating Issue",
    description: "The central heating is not working properly.",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Clogged Drain",
    description: "The bathroom sink is clogged.",
    request_date: 1695165600000,
    resolved_date: null,
    status: "in-progress",
    urgency: "medium",
  },
  {
    title: "Broken AC",
    description: "The air conditioning unit is not cooling.",
    request_date: 1695235200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Light Bulb Replacement",
    description: "Need to replace the bulb in the hallway.",
    request_date: 1695586500000,
    resolved_date: 1695586500000,
    status: "resolved",
    urgency: "low",
  },
  {
    title: "Garage Door Repair",
    description: "The garage door is not opening.",
    request_date: 1696040400000,
    resolved_date: null,
    status: "in-progress",
    urgency: "medium",
  },
  {
    title: "Roof Leak",
    description: "There is a leak in the roof during rain.",
    request_date: 1695868800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Pest Control",
    description: "Need pest control services for rodents.",
    request_date: 1695955200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Wall Painting",
    description: "The living room needs fresh paint.",
    request_date: 1695523200000,
    resolved_date: 1695926400000,
    status: "resolved",
    urgency: "low",
  },
  {
    title: "Squeaky Door",
    description: "The front door is squeaking when opened.",
    request_date: 1696057600000,
    resolved_date: null,
    status: "in-progress",
    urgency: "low",
  },
  {
    title: "Broken Dishwasher",
    description: "The dishwasher is not draining properly.",
    request_date: 1695696000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Faulty Smoke Detector",
    description: "The smoke detector keeps beeping.",
    request_date: 1695506400000,
    resolved_date: 1695592800000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Cracked Tile",
    description: "There is a cracked tile in the bathroom.",
    request_date: 1695213600000,
    resolved_date: null,
    status: "in-progress",
    urgency: "medium",
  },
  {
    title: "Fence Repair",
    description: "The back fence has fallen down.",
    request_date: 1696040400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Toilet Clog",
    description: "The toilet is clogged and not flushing.",
    request_date: 1695897600000,
    resolved_date: null,
    status: "in-progress",
    urgency: "high",
  },
  {
    title: "Hot Water Issue",
    description: "No hot water in the shower.",
    request_date: 1695908400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Paint Peeling",
    description: "Paint is peeling in the living room.",
    request_date: 1695379200000,
    resolved_date: 1695566400000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Wobbly Table",
    description: "The dining table is wobbly.",
    request_date: 1695586500000,
    resolved_date: null,
    status: "in-progress",
    urgency: "low",
  },
  {
    title: "Window Screen Repair",
    description: "The screen on the patio door is torn.",
    request_date: 1695696000000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Light Fixture Issue",
    description: "One of the light fixtures is flickering.",
    request_date: 1695820800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Garage Cleanup",
    description: "The garage needs to be cleaned and organized.",
    request_date: 1695974400000,
    resolved_date: 1696040400000,
    status: "resolved",
    urgency: "low",
  },
  {
    title: "Driveway Crack",
    description: "There is a significant crack in the driveway.",
    request_date: 1695506400000,
    resolved_date: null,
    status: "in-progress",
    urgency: "medium",
  },
  {
    title: "Outdoor Light Not Working",
    description: "The outdoor light near the entrance is not working.",
    request_date: 1695578400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Mold in Bathroom",
    description: "Mold is starting to grow in the shower area.",
    request_date: 1695868800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Broken Stairs",
    description: "The stairs leading to the basement are loose.",
    request_date: 1695897600000,
    resolved_date: null,
    status: "in-progress",
    urgency: "high",
  },
  {
    title: "Old Refrigerator",
    description: "The refrigerator is making a loud noise.",
    request_date: 1695458400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Flickering TV",
    description: "The living room TV keeps flickering.",
    request_date: 1695602400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Faucet Handle Broken",
    description: "The handle of the bathroom faucet is broken.",
    request_date: 1696012800000,
    resolved_date: null,
    status: "in-progress",
    urgency: "medium",
  },
  {
    title: "Backyard Drainage",
    description: "Water is pooling in the backyard.",
    request_date: 1696065600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Dishwasher Leak",
    description: "The dishwasher is leaking water onto the floor.",
    request_date: 1695249600000,
    resolved_date: null,
    status: "in-progress",
    urgency: "high",
  },
  {
    title: "Lawn Mowing",
    description: "The lawn needs to be mowed.",
    request_date: 1695379200000,
    resolved_date: 1695458400000,
    status: "resolved",
    urgency: "low",
  },
  {
    title: "Window Replacement",
    description: "The kitchen window needs to be replaced.",
    request_date: 1695561600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Carpet Cleaning",
    description: "The carpets need to be cleaned.",
    request_date: 1695724800000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Paving Stones Repair",
    description: "The paving stones in the walkway are uneven.",
    request_date: 1695820800000,
    resolved_date: null,
    status: "in-progress",
    urgency: "medium",
  },
  {
    title: "Broken Fence Gate",
    description: "The fence gate is broken and won't close.",
    request_date: 1695878400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Battery Replacement",
    description: "Need battery replacement for the smoke alarm.",
    request_date: 1695908400000,
    resolved_date: 1695974400000,
    status: "resolved",
    urgency: "low",
  },
  {
    title: "Leaking Roof",
    description: "The roof is leaking in the bedroom during rain.",
    request_date: 1695868800000,
    resolved_date: null,
    status: "in-progress",
    urgency: "high",
  },
  {
    title: "Basement Flooding",
    description: "The basement is flooded after heavy rain.",
    request_date: 1696012800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Stained Ceiling",
    description: "There are water stains on the ceiling.",
    request_date: 1696057600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Toilet Leak",
    description: "The toilet is leaking water onto the floor.",
    request_date: 1696135200000,
    resolved_date: null,
    status: "in-progress",
    urgency: "high",
  },
  {
    title: "Broken Hot Tub",
    description: "The hot tub is not heating up.",
    request_date: 1696040400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Outdated HVAC System",
    description: "The HVAC system is old and not functioning well.",
    request_date: 1696089600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Loose Railings",
    description: "The railings on the porch are loose.",
    request_date: 1696147200000,
    resolved_date: null,
    status: "in-progress",
    urgency: "medium",
  },
  {
    title: "Outdoor Grill Repair",
    description: "The outdoor grill is not igniting.",
    request_date: 1696233600000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Cracked Windshield",
    description: "The car's windshield has a crack.",
    request_date: 1696057600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Mailbox Repair",
    description: "The mailbox is damaged and needs repair.",
    request_date: 1696162800000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Shower Drain Clog",
    description: "The shower drain is clogged.",
    request_date: 1696177200000,
    resolved_date: null,
    status: "in-progress",
    urgency: "high",
  },
  {
    title: "Pet Door Installation",
    description: "Need a pet door installed.",
    request_date: 1696208400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Sump Pump Issue",
    description: "The sump pump is not functioning properly.",
    request_date: 1696245600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Landscape Maintenance",
    description: "The garden needs maintenance.",
    request_date: 1696303200000,
    resolved_date: 1696375200000,
    status: "resolved",
    urgency: "low",
  },
  {
    title: "Gutter Cleaning",
    description: "The gutters need to be cleaned.",
    request_date: 1696303200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Power Outlet Repair",
    description: "A power outlet is not working.",
    request_date: 1696177200000,
    resolved_date: null,
    status: "in-progress",
    urgency: "medium",
  },
  {
    title: "Cabinet Door Repair",
    description: "One of the cabinet doors is broken.",
    request_date: 1696310400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Torn Upholstery",
    description: "The couch upholstery is torn.",
    request_date: 1696348800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Ice Maker Not Working",
    description: "The ice maker in the fridge is not producing ice.",
    request_date: 1696416000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Window Lock Broken",
    description: "The lock on the bedroom window is broken.",
    request_date: 1696425600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Water Heater Repair",
    description: "The water heater is not heating water properly.",
    request_date: 1696492800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Sprinkler System Malfunction",
    description: "The sprinkler system is not turning on.",
    request_date: 1696531200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Ceiling Fan Installation",
    description: "Need a ceiling fan installed in the living room.",
    request_date: 1696531200000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Window Shade Replacement",
    description: "Need to replace the window shades in the bedroom.",
    request_date: 1696588800000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Deck Staining",
    description: "The deck needs to be stained.",
    request_date: 1696646400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Flooring Repair",
    description: "The flooring in the hallway is damaged.",
    request_date: 1696723200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Carpet Replacement",
    description: "Need to replace the carpet in the bedroom.",
    request_date: 1696723200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Home Security System",
    description: "Need to install a home security system.",
    request_date: 1696759200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "House Cleaning",
    description: "Need a deep cleaning of the house.",
    request_date: 1696759200000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Chimney Cleaning",
    description: "The chimney needs to be cleaned.",
    request_date: 1696828800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Tree Trimming",
    description: "Need to trim the overgrown tree in the backyard.",
    request_date: 1696886400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Furnace Repair",
    description: "The furnace is not heating the house properly.",
    request_date: 1696886400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Bathroom Sink Replacement",
    description: "The bathroom sink needs to be replaced.",
    request_date: 1696972800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Garage Organization",
    description: "The garage needs to be organized.",
    request_date: 1697011200000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Insulation Installation",
    description: "Need insulation installed in the attic.",
    request_date: 1697011200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Water Softener Repair",
    description: "The water softener is not functioning.",
    request_date: 1697078400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Garage Door Sensor Repair",
    description: "The garage door sensor is malfunctioning.",
    request_date: 1697116800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Shower Curtain Rod Installation",
    description: "Need a shower curtain rod installed.",
    request_date: 1697116800000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Key Replacement",
    description: "Need to replace the front door key.",
    request_date: 1697116800000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Towel Rack Installation",
    description: "Need to install a towel rack in the bathroom.",
    request_date: 1697174400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Siding Repair",
    description: "The siding on the house is damaged.",
    request_date: 1697241600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Pest Inspection",
    description: "Need a pest inspection done.",
    request_date: 1697308800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Pool Maintenance",
    description: "The pool needs maintenance.",
    request_date: 1697395200000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Dryer Vent Cleaning",
    description: "Need to clean the dryer vent.",
    request_date: 1697462400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Sewage Backup",
    description: "There is a sewage backup in the basement.",
    request_date: 1697462400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Appliance Installation",
    description: "Need to install a new refrigerator.",
    request_date: 1697548800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Gas Line Inspection",
    description: "Need to inspect the gas line for leaks.",
    request_date: 1697548800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Utility Sink Installation",
    description: "Need to install a utility sink in the garage.",
    request_date: 1697635200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Wind Damage Repair",
    description: "Repair needed for wind damage to the roof.",
    request_date: 1697635200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Deck Repair",
    description: "The deck is in need of repairs.",
    request_date: 1697635200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Radiator Leak",
    description: "The radiator is leaking.",
    request_date: 1697635200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Generator Maintenance",
    description: "Need to perform maintenance on the generator.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Hedge Trimming",
    description: "Need to trim the hedges in the front yard.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Mailbox Replacement",
    description: "The mailbox needs to be replaced.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Fence Painting",
    description: "The fence needs to be painted.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Ceiling Repair",
    description: "There is damage to the ceiling that needs repair.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Shower Head Replacement",
    description: "Need to replace the shower head.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Radiator Repair",
    description: "The radiator is not heating properly.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Storm Door Installation",
    description: "Need to install a storm door.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Outdoor Furniture Assembly",
    description: "Need to assemble the outdoor furniture.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Interior Painting",
    description: "Need to paint the interior of the house.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Fireplace Inspection",
    description: "Need to inspect the fireplace for safety.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Basement Cleanup",
    description: "The basement needs to be cleaned out.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Window Cleaning",
    description: "Need to clean the windows.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Radiator Installation",
    description: "Need to install a new radiator.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Shower Grout Cleaning",
    description: "Need to clean the grout in the shower.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Washing Machine Repair",
    description: "The washing machine is not working.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Pool Repair",
    description: "Need to repair the pool pump.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Home Insulation Inspection",
    description: "Need to inspect home insulation.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Roof Inspection",
    description: "Need a roof inspection.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Fence Replacement",
    description: "Need to replace the old fence.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Window Replacement",
    description: "Need to replace the broken window.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Door Lock Installation",
    description: "Need to install a new door lock.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Electrical Wiring Inspection",
    description: "Need to inspect electrical wiring for safety.",
    request_date: 1697702400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Garage Door Repair",
    description: "The garage door is not opening properly.",
    request_date: 1697779200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Pond Cleaning",
    description: "The pond needs to be cleaned out.",
    request_date: 1697865600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Light Fixture Replacement",
    description: "Need to replace a broken light fixture.",
    request_date: 1697952000000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Wall Repair",
    description: "There is a hole in the wall that needs repair.",
    request_date: 1698038400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Appliance Repair",
    description: "The dishwasher is not cleaning properly.",
    request_date: 1698124800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Window Screen Repair",
    description: "One of the window screens is torn.",
    request_date: 1698211200000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Heating System Inspection",
    description: "Need to inspect the heating system for issues.",
    request_date: 1698297600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Gutter Repair",
    description: "One of the gutters is leaking.",
    request_date: 1698384000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Bathroom Mold Inspection",
    description: "Check for mold in the bathroom area.",
    request_date: 1698470400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Driveway Sealing",
    description: "The driveway needs to be sealed.",
    request_date: 1698556800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Shed Repair",
    description: "The shed door is broken.",
    request_date: 1698643200000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Pest Control",
    description: "Need pest control for ants in the kitchen.",
    request_date: 1698729600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Fire Alarm Testing",
    description: "Need to test the fire alarms.",
    request_date: 1698816000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Bathroom Vanity Replacement",
    description: "The bathroom vanity needs to be replaced.",
    request_date: 1698902400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Attic Insulation",
    description: "The attic needs additional insulation.",
    request_date: 1698988800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Faucet Repair",
    description: "The kitchen faucet is leaking.",
    request_date: 1699075200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Broken Staircase",
    description: "One of the steps on the staircase is broken.",
    request_date: 1699161600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Mailbox Installation",
    description: "Need a new mailbox installed.",
    request_date: 1699248000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Carport Repair",
    description: "The carport roof is leaking.",
    request_date: 1699334400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Electric Panel Upgrade",
    description: "Need to upgrade the electric panel.",
    request_date: 1699420800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Chandelier Installation",
    description: "Need to install a new chandelier in the dining room.",
    request_date: 1699507200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Fence Installation",
    description: "Need to install a new fence in the backyard.",
    request_date: 1699593600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Crawl Space Inspection",
    description: "Need to inspect the crawl space for issues.",
    request_date: 1699680000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Wall Insulation",
    description: "Need insulation added to the exterior walls.",
    request_date: 1699766400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Cabinet Installation",
    description: "Need to install new kitchen cabinets.",
    request_date: 1699852800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Smoke Detector Installation",
    description: "Install smoke detectors in all bedrooms.",
    request_date: 1699939200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Shower Door Installation",
    description: "Need to install a new shower door.",
    request_date: 1700025600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Sump Pump Installation",
    description: "Need to install a sump pump in the basement.",
    request_date: 1700112000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Fire Pit Construction",
    description: "Need to construct a fire pit in the backyard.",
    request_date: 1700198400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Deck Installation",
    description: "Need to install a new deck.",
    request_date: 1700284800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Patio Repair",
    description: "The patio is cracking and needs repair.",
    request_date: 1700371200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Backyard Landscaping",
    description: "Need landscaping work done in the backyard.",
    request_date: 1700457600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Pressure Washing",
    description: "Need to pressure wash the exterior of the house.",
    request_date: 1700544000000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Air Duct Cleaning",
    description: "Need to clean the air ducts.",
    request_date: 1700630400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Roof Cleaning",
    description: "Need to clean the roof.",
    request_date: 1700716800000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Thermostat Replacement",
    description: "Need to replace the thermostat.",
    request_date: 1700803200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Backyard Shed Construction",
    description: "Need to build a shed in the backyard.",
    request_date: 1700889600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "New Appliance Delivery",
    description: "Schedule delivery for new appliances.",
    request_date: 1700976000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Garage Cleaning",
    description: "The garage needs a thorough cleaning.",
    request_date: 1701062400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Foundation Inspection",
    description: "Need to inspect the foundation for cracks.",
    request_date: 1701148800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Outdoor Lighting Installation",
    description: "Need to install outdoor lighting.",
    request_date: 1701235200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Gutter Cleaning",
    description: "Need to clean the gutters.",
    request_date: 1701321600000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Crown Molding Installation",
    description: "Need to install crown molding in the living room.",
    request_date: 1701408000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Home Theater Installation",
    description: "Need to install a home theater system.",
    request_date: 1701494400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Home Office Setup",
    description: "Need to set up a home office.",
    request_date: 1701580800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "House Pressure Testing",
    description: "Need to perform a pressure test on the house.",
    request_date: 1701667200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Wall Painting",
    description: "Need to paint the walls in the living room.",
    request_date: 1701753600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Driveway Repair",
    description: "The driveway has cracks that need repair.",
    request_date: 1701840000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Electrician Needed",
    description: "Need an electrician for various jobs.",
    request_date: 1701926400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Chimney Cap Installation",
    description: "Need to install a chimney cap.",
    request_date: 1702012800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Patio Furniture Assembly",
    description: "Need to assemble new patio furniture.",
    request_date: 1702099200000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Basement Renovation",
    description: "Need to renovate the basement.",
    request_date: 1702185600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Pet Door Installation",
    description: "Need to install a pet door.",
    request_date: 1702272000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Wine Cellar Construction",
    description: "Need to construct a wine cellar.",
    request_date: 1702358400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Solar Panel Installation",
    description: "Need to install solar panels on the roof.",
    request_date: 1702444800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Security System Installation",
    description: "Need to install a new security system.",
    request_date: 1702531200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Patio Pavers Installation",
    description: "Need to install pavers on the patio.",
    request_date: 1702617600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Ceiling Fan Installation",
    description: "Need to install a ceiling fan in the bedroom.",
    request_date: 1702704000000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Window Tinting",
    description: "Need to tint the windows for better privacy.",
    request_date: 1702790400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "New Carpet Installation",
    description: "Need to install new carpet in the living room.",
    request_date: 1702876800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Siding Repair",
    description: "Need to repair damaged siding on the house.",
    request_date: 1702963200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Wall-to-Wall Carpet Cleaning",
    description: "Need to clean the wall-to-wall carpeting.",
    request_date: 1703049600000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Indoor Plant Care",
    description: "Need to take care of indoor plants.",
    request_date: 1703136000000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Air Conditioner Tune-Up",
    description: "Need to service the air conditioning unit.",
    request_date: 1703222400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Dryer Vent Cleaning",
    description: "Need to clean the dryer vent.",
    request_date: 1703308800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Sprinkler System Repair",
    description: "Need to repair the sprinkler system.",
    request_date: 1703395200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Attic Fan Installation",
    description: "Need to install an attic fan.",
    request_date: 1703481600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Brick Repair",
    description: "Need to repair damaged bricks on the exterior.",
    request_date: 1703568000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Garage Organization",
    description: "Need help organizing the garage.",
    request_date: 1703654400000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Countertop Installation",
    description: "Need to install new kitchen countertops.",
    request_date: 1703740800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Window Seal Replacement",
    description: "Need to replace window seals.",
    request_date: 1703827200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Pool Deck Resurfacing",
    description: "Need to resurface the pool deck.",
    request_date: 1703913600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Outdoor Kitchen Installation",
    description: "Need to install an outdoor kitchen.",
    request_date: 1704000000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Bathroom Tile Replacement",
    description: "Need to replace tiles in the bathroom.",
    request_date: 1704086400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Pavement Sealing",
    description: "Need to seal the pavement in the driveway.",
    request_date: 1704172800000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Childproofing",
    description: "Need to childproof the house.",
    request_date: 1704259200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Utility Room Renovation",
    description: "Need to renovate the utility room.",
    request_date: 1704345600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Fireplace Cleaning",
    description: "Need to clean the fireplace.",
    request_date: 1704432000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Whole House Fan Installation",
    description: "Need to install a whole house fan.",
    request_date: 1704518400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Landscape Lighting",
    description: "Need to install landscape lighting.",
    request_date: 1704604800000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Wood Floor Installation",
    description: "Need to install wood floors in the living room.",
    request_date: 1704691200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Septic System Inspection",
    description: "Need to inspect the septic system.",
    request_date: 1704777600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Toilet Installation",
    description: "Need to install a new toilet.",
    request_date: 1704864000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Radiant Floor Heating Installation",
    description: "Need to install radiant floor heating.",
    request_date: 1704950400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Gutter Downspout Extension",
    description: "Need to extend the downspouts.",
    request_date: 1705036800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Solar Water Heater Installation",
    description: "Need to install a solar water heater.",
    request_date: 1705123200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Deck Staining",
    description: "Need to stain the wooden deck.",
    request_date: 1705209600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Pond Installation",
    description: "Need to install a pond in the backyard.",
    request_date: 1705296000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Pool Heater Installation",
    description: "Need to install a pool heater.",
    request_date: 1705382400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Carport Construction",
    description: "Need to construct a carport.",
    request_date: 1705468800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Driveway Resurfacing",
    description: "Need to resurface the driveway.",
    request_date: 1705555200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Interior Design Consultation",
    description: "Need an interior designer for consultation.",
    request_date: 1705641600000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Home Automation System Setup",
    description: "Need to set up a home automation system.",
    request_date: 1705728000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Attic Storage Installation",
    description: "Need to install storage in the attic.",
    request_date: 1705814400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Fence Repair",
    description: "Need to repair a damaged fence.",
    request_date: 1705900800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Tree Removal",
    description: "Need to remove a dead tree in the yard.",
    request_date: 1705987200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Outdoor Shower Installation",
    description: "Need to install an outdoor shower.",
    request_date: 1706073600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Garage Door Opener Installation",
    description: "Need to install a new garage door opener.",
    request_date: 1706160000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Home Theater Setup",
    description: "Need to set up a home theater system.",
    request_date: 1706246400000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Sump Pump Maintenance",
    description: "Need to maintain the sump pump.",
    request_date: 1706332800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Kitchen Remodel",
    description: "Need to remodel the kitchen.",
    request_date: 1706419200000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Garage Floor Coating",
    description: "Need to apply a coating to the garage floor.",
    request_date: 1706505600000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Storm Door Installation",
    description: "Need to install a storm door.",
    request_date: 1706592000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Hot Tub Installation",
    description: "Need to install a hot tub in the backyard.",
    request_date: 1706678400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Roof Ventilation",
    description: "Need to install ventilation on the roof.",
    request_date: 1706764800000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Fence Painting",
    description: "Need to paint the wooden fence.",
    request_date: 1706851200000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Ductless AC Installation",
    description: "Need to install a ductless AC unit.",
    request_date: 1706937600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Water Softener Installation",
    description: "Need to install a water softener.",
    request_date: 1707024000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Playground Installation",
    description: "Need to install a playground set in the yard.",
    request_date: 1707110400000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "New Roof Installation",
    description: "Need to install a new roof.",
    request_date: 1707196800000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Home Exterior Painting",
    description: "Need to paint the exterior of the house.",
    request_date: 1707283200000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Exterior Door Replacement",
    description: "Need to replace the exterior door.",
    request_date: 1707369600000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Leaky Faucet",
    description: "Fix the leak in the kitchen",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Broken Window",
    description: "Replace window in the living room",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Heating Issue",
    description: "Heater not working",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Roof Leak",
    description: "Water leaking from the roof",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Bathroom Remodel",
    description: "Renovate the bathroom",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Electrical Issue",
    description: "Flickering lights in hallway",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Leaky Roof",
    description: "Need to fix the roof leak",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Cabinet Repair",
    description: "Fix the kitchen cabinet door",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "medium",
  },
  {
    title: "Wall Painting",
    description: "Paint the living room walls",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Clogged Drain",
    description: "Unclog the kitchen sink",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Door Lock Issue",
    description: "Fix the front door lock",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Garden Maintenance",
    description: "Trim the bushes and mow the lawn",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "low",
  },
  {
    title: "Appliance Repair",
    description: "Fix the refrigerator",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Lighting Upgrade",
    description: "Upgrade hallway lighting to LEDs",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Window Repair",
    description: "Repair broken window in bedroom",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "low",
  },
  {
    title: "Squeaky Door",
    description: "Fix squeaky door in the hallway",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Thermostat Malfunction",
    description: "Thermostat not regulating temperature",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Fence Repair",
    description: "Repair broken fence",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "medium",
  },
  {
    title: "Gutter Cleaning",
    description: "Clean out the gutters",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "low",
  },
  {
    title: "Paint Touch-Up",
    description: "Touch up paint in various areas",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "low",
  },
  {
    title: "Deck Repair",
    description: "Fix loose boards on the deck",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Bathroom Plumbing",
    description: "Fix plumbing issues in the bathroom",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Basement Leak",
    description: "Fix leak in the basement",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Smoke Detector Check",
    description: "Check and replace smoke detector batteries",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "low",
  },
  {
    title: "Chipped Tile",
    description: "Replace chipped tile in kitchen",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Heating System Maintenance",
    description: "Perform maintenance on heating system",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Garage Door Repair",
    description: "Fix the garage door opener",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Insulation Installation",
    description: "Install insulation in the attic",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Crown Molding Installation",
    description: "Install crown molding in living room",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Appliance Installation",
    description: "Install new dishwasher",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "low",
  },
  {
    title: "Carpet Cleaning",
    description: "Clean carpets throughout the house",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "low",
  },
  {
    title: "Dryer Vent Cleaning",
    description: "Clean out dryer vent",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Pest Control",
    description: "Address pest issues in the house",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Roof Inspection",
    description: "Inspect roof for damage",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "low",
  },
  {
    title: "Window Sealing",
    description: "Seal windows to prevent drafts",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Flooring Repair",
    description: "Repair damaged flooring in living room",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "high",
  },
  {
    title: "Patio Furniture Assembly",
    description: "Assemble patio furniture",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "low",
  },
  {
    title: "TV Mounting",
    description: "Mount TV on living room wall",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Siding Repair",
    description: "Repair damaged siding on the house",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Door Replacement",
    description: "Replace front door",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "medium",
  },
  {
    title: "Shower Leak",
    description: "Fix leak in shower",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Basement Insulation",
    description: "Insulate basement walls",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Backyard Clean-Up",
    description: "Clean up the backyard",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "low",
  },
  {
    title: "Window Tinting",
    description: "Tint windows in the house",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Power Washing",
    description: "Power wash the exterior of the house",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "low",
  },
  {
    title: "Water Heater Replacement",
    description: "Replace old water heater",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Radiator Fix",
    description: "Fix radiator in living room",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "medium",
  },
  {
    title: "Fireplace Inspection",
    description: "Inspect and clean fireplace",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Playground Installation",
    description: "Install playground set in the yard",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "high",
  },
  {
    title: "Sprinkler System Repair",
    description: "Fix broken sprinkler system",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "high",
  },
  {
    title: "Furnace Maintenance",
    description: "Perform maintenance on furnace",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "House Cleaning",
    description: "Deep clean the entire house",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "low",
  },
  {
    title: "Gutter Repair",
    description: "Repair damaged gutters",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "resolved",
    urgency: "medium",
  },
  {
    title: "Wall Repair",
    description: "Fix hole in the wall",
    request_date: 1694244000000,
    resolved_date: null,
    status: "pending",
    urgency: "medium",
  },
  {
    title: "Outdoor Lighting Installation",
    description: "Install lights in the backyard",
    request_date: 1694244000000,
    resolved_date: 1694247600000,
    status: "closed",
    urgency: "low",
  },
];

export const features = [
  {
    title: "AI-Powered Troubleshooting",
    description:
      "Properly's AI-powered chatbot, Bri, helps tenants resolve common maintenance issues quickly, reducing unnecessary escalations and saving time for both tenants and property managers.",
  },
  {
    title: "Real-Time Updates",
    description:
      "Instant notifications keep tenants and property managers informed at every step, ensuring transparency and minimizing delays or confusion.",
  },
  {
    title: "Integrated Feedback Loop",
    description:
      "Gather tenant feedback after issue resolution to improve service quality and quickly address any disputes, maintaining high tenant satisfaction.",
  },
  {
    title: "White-Label Solutions",
    description:
      "Customize Properly to match your brand, providing a seamless experience for tenants while maintaining your unique identity.",
  },
  {
    title: "Partnering with Service Providers",
    description:
      "Easily integrate external service providers to handle complex maintenance tasks, ensuring faster and more efficient resolutions.",
  },
  // {
  //   title: "Visual Documentation",
  //   description:
  //     "Tenants can upload photos or videos of issues for faster diagnosis.",
  // },
];

export const faqs = [
  {
    question: "What types of properties can I manage with Properly?",
    answer:
      "Properly is designed for various property types, including residential, commercial, and multi-family units.",
  },

  {
    question: "How does the pricing structure work?",
    answer:
      "We offer tiered pricing plans based on the number of properties managed and additional tenant capacities. Contact us for specific details on our packages.",
  },

  {
    question: "Can tenants access Properly on mobile devices?",
    answer:
      "Yes, Properly is accessible via mobile devices, allowing tenants to submit requests and receive updates on the go.",
  },

  {
    question:
      "What happens if a tenant experiences a maintenance issue after hours?",
    answer:
      "Tenants can submit requests at any time, and property managers will be notified immediately. The platform enables communication to address urgent issues promptly.",
  },
  {
    question: "How does Properly help tenants with maintenance requests?",
    answer:
      "Submit requests quickly, upload photos or videos for clarity, and track the progress in real-time. This ensures transparency and reduces the likelihood of delays or miscommunication.",
  },

  {
    question: "How do I train my team to use Properly?",
    answer:
      "We provide comprehensive onboarding support and training materials to ensure your team can effectively use the platform from day one.",
  },

  {
    question:
      "Can I integrate Properly with my existing property management systems?",
    answer:
      "Yes! Properly offers integration options to help streamline your operations and enhance functionality with your current systems.",
  },

  {
    question: "How does Properly handle tenant feedback?",
    answer:
      "Properly collects and analyzes tenant feedback through automated surveys, helping you identify areas for improvement and enhance service quality.",
  },

  {
    question: "What if I need assistance with Properly?",
    answer:
      "Our customer support team is available to assist you with any questions or issues you may encounter while using the platform.",
  },

  {
    question: "Is there a free trial available?",
    answer:
      "Yes! We offer a free trial period so you can explore Properly's features and see how it fits your property management needs.",
  },

  {
    question: "How do I get started with Properly?",
    answer:
      "To get started, simply reach out to us through our website, and our team will guide you through the setup process!",
  },
];

export const properlyWhys = [
  {
    name: "AI Chatbot Bri",
    description:
      "Meet Bri, the smart assistant that helps tenants fix minor issues themselves, cutting down property managers’ workloads and speeding up solutions. Enhance efficiency, improve tenant satisfaction, and simplify property management with Bri.",
    icon: "chatbot.png",
  },
  {
    name: "Automated Feedback Loop",
    description:
      "Enhance your property management with Properly’s Automated Feedback Loop, collecting instant tenant feedback to drive service improvements and foster loyalty.",
    icon: "loop.png",
  },
  {
    name: "Real-time Communication",
    description:
      "Enjoy instant notifications for efficient issue reporting and maintenance tracking, ensuring no concern goes unnoticed and every task is addressed promptly. Transform your property management experience today!.",
    icon: "communik.png",
  },
  {
    name: "Prevent Legal and Financial Risks",
    description:
      "Properly ensures timely issue resolution, reducing legal liabilities and financial risks. Protect your operations today!.",
    icon: "legal.png",
  },
];
